# Generated by Django 5.2.3 on 2025-07-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahasalamana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanafody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anarana', models.CharField(max_length=200)),
                ('famaritana', models.TextField()),
                ('vidiny', models.PositiveIntegerField()),
                ('sary', models.ImageField(blank=True, null=True, upload_to='sary_fanafody/')),
                ('daty_nampidirana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
