# Generated by Django 5.2.3 on 2025-07-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahasalamana', '0002_fanafody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sosokevitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lohateny', models.CharField(max_length=200)),
                ('ambara', models.CharField(max_length=500)),
                ('sary', models.ImageField(blank=True, null=True, upload_to='sary_sosokevitra/')),
                ('daty_nampidirana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
