# Generated by Django 5.2.3 on 2025-07-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahasalamana', '0003_sosokevitra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosokevitra',
            name='ambara',
            field=models.TextField(blank=True),
        ),
    ]
